### ISSUE TITLE
Article "/2017/05/le-rendez-vous/"

### ISSUE THREAD

**Issue by KewlCat** [borisschapira/blog#13]
Hello Boris

Petit souci lors du passage "Personne ne dit rien. Il silence pesant s’installe" => "Le" silence s'installe

C'est tout.

Au début j'ai cru que "encadrure" était le produit de "encadrement + encâblure" mais je découvre que c'est un synonyme d'encadrement donc j'aurai appris quelque chose ;-)

**Comment by borisschapira** [comment]
Merci !

**Comment by borisschapira** [comment]
C'est corrigé :)
