### ISSUE TITLE
Article "/2017/05/a-l-aventure/"

### ISSUE THREAD

**Issue by sdeschamps-orange** [borisschapira/blog#16]
Salut patron,

[Une issue pas liée](https://github.com/Orange-OpenSource/a11y-guidelines/issues/7) nous apprend que le lien https://github.com/borisschapira/blog/blob/master/f/default/2017/2017-05-31-a-l-aventure/2017-05-31-a-l-aventure.md est aux abonnés absents.

Bien à vous cher Monsieur,
Votre Très Dévoué :stuck_out_tongue:

**Comment by borisschapira** [comment]
Fixed by https://github.com/borisschapira/jekyll-bs/commit/e54224fc50c398e7edbd193201a4959f79d13619, thanks !
