### ISSUE TITLE
Petit soucis sur la pagination dans une catégorie

### ISSUE THREAD

**Issue by ryuran** [borisschapira/blog#20]
Quand je suis sur la page https://borisschapira.com/papa/ et que je clique sur le lien de la page `2`
Je me retrouve sur la page `2` du site https://borisschapira.com/page/2/ au lieu de https://borisschapira.com/papa/page/2/.

**Comment by borisschapira** [comment]
Oh, merci, je n'avais pas vu. C'est corrigé :)
