### ISSUE TITLE
Article "/2016/06/la-blockchain-expliquee-a-un-enfant-de-cinq-ans/"

### ISSUE THREAD

**Issue by oncletom** [borisschapira/blog#5]
Hey hey hey !

Rien de méchant mais deux p'tits soucis avec cet article :

- `s/collectif Blockain France/collectif Blockchain France/`
- et pis j'l'ai pas trouvé dans le repo git donc j'ai pas pu proposer une PR (ça sent l'article posé sur ton ordi mais pas poussé sur GitHub)

Voilou :-)

**Comment by borisschapira** [comment]
Hey, merci pour la coquille, c'est corrigé. J'ai réalimenté le dépôt aussi :)
