### ISSUE TITLE
Article "/2016/12/le-web-au-futur/" : ajouter des ressources

### ISSUE THREAD

**Issue by antoinentl** [borisschapira/blog#8]
Je propose d'ajouter la référence du livre de Jeremy Keith, *Resilient Web Design*, [https://resilientwebdesign.com/](https://resilientwebdesign.com/), dans une partie "Ressources" de cet article.

D'autres ressources pourraient être également ajoutées, mais cela alourdira peut-être les propos (le texte est très fluide sous cette forme), en vrac :

- [The Future Web Wants You.](https://briankardell.wordpress.com/2016/08/24/the-future-web-wants-you/) par Brian Kardell ;
- [The Future of the Web](http://alistapart.com/article/the-future-of-the-web) par Matt Griffin ;
- [Arrêtez le Web](http://www.la-grange.net/2015/08/04/stop) par Karl Dubost.

**Comment by borisschapira** [comment]
Très bonnes propositions. J'intègre dès que j'ai un peu de temps. Merci !

**Comment by borisschapira** [comment]
En cours de build 👍  (at last)

**Comment by antoinentl** [comment]
:+1:
